// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/compare-version/compare-version.d.ts
declare module 'compare-version' {
  function compare(a: string, b: string): number;

  export = compare;
}
