// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/graceful-fs/graceful-fs.d.ts
declare module 'graceful-fs' {
	import fs = require('fs');
	export = fs;
}
